auth.py
import datetime
import json
import string
import random

#import self as self
import sqlalchemy
from flask import render_template, url_for, redirect, Blueprint, request, flash
import requests
import os
from flask_login import login_user, logout_user, login_required, current_user
from wtforms.validators import InputRequired, Length, ValidationError
from __init__ import db, bcrypt, login_manager
from forms import RegisterForm, LoginForm, UpdateAccountForm, ValidateAccount, ConversionForm
from database_models import User, PaymentCard, OnlineAccount
from database_functions import get_user_by_username, get_payment_card, update_user_data, update_user_data_verification, get_online_account, get_user_by_email
from transaction import payoff_from_payment_card



auth = Blueprint('auth', __name__)


@login_manager.user_loader  # reload user obj from the user id stored in the session
def load_user(user_id):
    return User.query.get(user_id)


@auth.route('/login', methods=['GET', 'POST'])
def login(login_error=None):
    form = LoginForm()
    if not form.validate_on_submit():
        return render_template('login.html', form=form)
    else:
        user = get_user_by_email(form.email.data)
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            load_user(user.id)
            login_user(user)
            return redirect(url_for('views.dashboard'))
        else:
            error_message = 'wrong email or password'
            return render_template('login.html',error_message =  error_message, form = form)


@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/status')
@login_required
def status():  # this function check if user account is verified
    user = get_user_by_username(current_user.username)
    online_account = get_online_account(user.onlineCardNumber)
    if user.is_verified:
        return render_template('statusCheck.html', visibility="hidden", balance=online_account.balance)
    else:
        return render_template('statusCheck.html', visibility="visible", balance=0)


@auth.route('/account_verification', methods=['GET', 'POST'])
@login_required
def account_verification():
    form = ValidateAccount()
    if request.method == 'GET':
        return render_template('accountVerification.html', form=form)
    else:
        card_number = form.card_number
        print(card_number.data)
        # PaymentCard.pay_in(1,card_number.data)
        if not current_user.validate_card_number(card_number):
            error_message = 'Uneli ste neispravan broj kartice. Pokusajte ponovo.'
            return render_template('accountVerification.html',error_message =  error_message, form = form)
        else:
            if payoff_from_payment_card(1, card_number.data):  # payoff one dollar
                current_user.verified = True
                update_user_data_verification(current_user)
                db.session.commit()
                return redirect(url_for('auth.status'))
            else:
                error_message = 'Nemate dovoljan iznos na vasem racunu. Neuspesna verifikacija.'
                return render_template('accountVerification.html',error_message =  error_message, form = form)
        

@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        #TODO check if mail exists alredy
        username = save_user_data(form)
        user = User.query.filter_by(username=username).first()
        user.cardNumber = create_payment_card(user.id, user.username)
        user.onlineCardNumber = create_online_account(user.username, user.email)
        db.session.commit()
        return redirect(url_for('auth.login'))
    #error_message = form.errors
    return render_template('register.html', form=form)


def save_user_data(form):  # used to save user data into db used only for creating new users
    hashed_password = bcrypt.generate_password_hash(form.password.data)

    new_user = User(username=form.username.data, first_name=form.first_name.data, last_name=form.last_name.data,
                    address=form.address.data, town=form.town.data, country=form.country.data,
                    phone_number=form.phone_number.data, cardNumber=1, onlineCardNumber=1, email=form.email.data,
                    verified=False, password=hashed_password)

    db.session.add(new_user)
    db.session.commit()

    return new_user.username


def create_payment_card(user_id, username):
    payment_card = PaymentCard()
    _accountNum = ''.join(random.choices(string.digits, k=18))
    while account_num_exists(_accountNum):
        _accountNum = ''.join(random.choices(string.digits, k=18))
    _security_code = ''.join(random.choices(string.digits, k=3))
    _expiry_date = datetime.datetime.today() + datetime.timedelta(days=730)

    payment_card.card_number = _accountNum
    payment_card.security_code = _security_code
    payment_card.balance = 0
    payment_card.user_id = user_id
    payment_card.user_name = username
    payment_card.balance = 100  # TODO da li na pocetku dodati malu sumu?
    payment_card.id = id(payment_card)  # unique integer number for every unique value it is used with.
    year = str(_expiry_date.month) + '/' + str(_expiry_date.year)[2:]
    payment_card.expiry_data = year

    db.session.add(payment_card)
    db.session.commit()
    return _accountNum


def create_online_account(username, email):
    online_account = OnlineAccount()
    _accountNum = ''.join(random.choices(string.digits, k=18))
    while account_num_exists(_accountNum):
        _accountNum = ''.join(random.choices(string.digits, k=18))

    online_account.card_number = _accountNum
    online_account.balance = 0
    online_account.user_email = email
    online_account.user_name = username
    online_account.balance = 0
    online_account.id = id(online_account)  # unique integer number for every unique value it is used with.

    db.session.add(online_account)
    db.session.commit()
    return _accountNum


#  Check if user with same account number already exists
#  We do this because account number is randomly generated and must be unique
def account_num_exists(acc_num):
    account = get_payment_card(acc_num)
    if account:
        return True
    else:
        return False


# edit profile
@auth.route('/editProfile', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        update_user_data(form, current_user)
        return redirect(url_for('views.dashboard'))
    elif request.method == 'GET':
        print(current_user)
        form.username.data = current_user.username
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.address.data = current_user.address
        form.town.data = current_user.town
        form.country.data = current_user.country
        form.phone_number.data = current_user.phone_number
        form.email.data = current_user.email
        form.password.data = current_user.password

    return render_template('editProfile.html', form=form)


@auth.route('/dashboard', methods=['GET', 'POST'])
@login_required
def back():
    return redirect(url_for('views.dashboard'))

# @auth.route('/pay_in')
# @login_required
# def pay_in():
#     return render_template('payIn.html')
#
# @auth.route('/history')
# @login_required
# def history():
#     return render_template('history.html')

#  db access function


if 'API_KEY' in os.environ:
    API_KEY = os.environ['API_KEY']
else:
    API_KEY = '34XNFFOAI313821W'


@auth.route('/convert', methods=["POST", "GET"])
@login_required
def convert():
    form =ConversionForm()
    currencies = getCurrenciesList()
    if request.method == 'POST':
        selecetd_currency = request.form.get("inputValuta")
        amount = request.form.get("inputKolicina")
        print(amount)
        print(selecetd_currency)
        rate = getSelectedCurrency(selecetd_currency)
        print(rate)



        acc =get_online_account(current_user.onlineCardNumber)
        if(int(acc.balance) >= int(amount)):
            converted_amount = float(amount)/rate

            # check if column alredy exists if not create new column
            columns = [i[1] for i in db.engine.execute('PRAGMA table_info(online_account)')]
            if selecetd_currency not in columns:
                db.engine.execute('''alter table online_account add ''' + selecetd_currency)

            # inser a value intp a column
            db.engine.execute("UPDATE online_account set " + selecetd_currency +" = " + str(converted_amount) + " where id = " + str(acc.id))

            acc.balance -= int(amount);
            db.session.commit();
            return redirect(url_for("auth.balances"))

        else:
            error_message = "Nemate dovoljno novca "
            return render_template("convert.html", currencies=currencies, form=form , error_message=error_message)

    else:
        return render_template("convert.html", currencies=currencies, form=form)
    #print(form.amount)


# get from db blance in all currencies
@auth.route('/balances', methods=["POST", "GET"])
@login_required
def balances():
    class item():
        def __init__(self, currency: str, value: int):
            self.currency = currency
            self.value = value

    acc = get_online_account(current_user.onlineCardNumber)
    my_accounts = []

    columns = [i[1] for i in db.engine.execute('PRAGMA table_info(online_account)')]
    columns = columns[5:]

    for x in columns:
        if x == 'EUR':
            it = item(x, acc.EUR)
        elif x == 'USD':
            it = item(x, acc.USD)
        elif x == 'ADA':
            it = item(x, acc.ADA)
        elif x == 'AED':
            it = item(x, acc.AED)
        elif x == 'AFN':
            it = item(x, acc.AFN)
        elif x == 'AMG':

templates/Index.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device=width, initial-scale=1.0">
    <title>LOG IN</title>
    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
            background: center/cover  url("../static/bankingg.webp") fixed no-repeat;

        }
        html {
            height: 100%;
            background-color: #03c6fc;
        }


        h1{
            
            font-size: 50px;
            color: white;
            font-family: serif;
        }


        a{
            text-align: center;
            font-size: 20px;
            position: relative;
            left: 120px;
            font-family: serif;
            color: white;
        }
        h2{
            text-align: center;
            font-size: 30px;
            position: relative;
            font-family: serif;
            color: white;
        }
        .outer {
            display: grid;
            grid-template: 1fr / 1fr;
            
          }
          .outer > * {
            grid-column: 1 / 1;
            grid-row: 1 / 1;
          }
          .outer .div1 {
            height: 70px;
            width: 20%;      
            border: 0px outset #04122b;
      
            position: relative;
            left: 180px;
            top: 10px;
          }
          .outer .div2 {
            height: 200px;
            width: 30%;
            border: 2px outset beige ;
            
            text-align: center;
            position: relative;
            left: 110px;
            top: 220px;
          }
        
    </style>    
</head>
<body>
<div class="outer">
    <div class="div1">
        <a href="{{url_for('auth.login')}}">Prijavi se</a> <br>
        <br>
        <a href="{{url_for('auth.register')}}">Registruj se</a>
    </div>
    <br>
    <div class="div2">
        <h1>Zdravo!</h1>
        <h2>Dobrodošli u našu banku!</h3>
    </div>
</div>
</body>
</html>

templates/accountVerification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Provera statusa</title>
    <style>
      body, html
      {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;

      }
      a:link, a:visited {
        color: #221647;
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
      }
      p{
        font-family: serif;
        font-size:25px;
        color: #221647;
      }
      a:hover{
        border:1px solid black;  
       }
       h1{
        text-align: center;   
        font-size: 40px;
        color: #221647;
        font-family: serif;
    }
    .myDiv{
      height: 300px;
      width: 20%;
      border: 3px outset #221647 ;
      text-align: center;
      position: relative;
      top: 50px;
      left: 600px;
      
  }
  table, th, td {
    border:1px solid black;
    

  }
  .button {
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
  
  .button1 {background-color: #008CBA;} /* Blue */
    </style>
</head>
<body>
  <h1>Verifikacija naloga</h1>
  <div class="myDiv">
    <br>

    <form method="POST" action="">
          <label> Unesite broj kartice</label><br>
          {{ form.card_number }}<br><br>
         {{ form.submit() }}
      </form>
  <br>
  {% if error_message %}
  <p style="color:red">{{ error_message }}</p>
  {% endif %} 
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <a href="{{url_for('auth.back')}}">Vrati se na prethodnu stranicu </a>
  </div>
</body>
</html>

templates/balances.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Provera statusa</title>
    <style>
      body, html
      {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;

      }
      a:link, a:visited {
        color: #221647;
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
      }
      p{
        font-family: serif;
        font-size:25px;
        color: #221647;
      }
      a:hover{
        border:1px solid black;  
       }
       h1{
        text-align: center;   
        font-size: 40px;
        color: #221647;
        font-family: serif;
    }
    .myDiv{
      height: 300px;
      width: 20%;
      border: 3px outset #221647 ;
      text-align: center;
      position: relative;
      top: 50px;
      left: 600px;
      
  }
  table, th, td {
    border:1px solid black;
    background-color:white;

  }
  .button {
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
  
  .button1 {background-color: #008CBA;} /* Blue */
  .button2 {background-color: #5c0000;}
    </style>
</head>
<body>
  <h1>Pregled stanja računa</h1>
<!--treba dodati logiku da li je novi korisnik ili stari, trenutno se podrazumijeva da je novi-->
  <div class="myDiv">
    <br>
  <table width="90%" style="margin: 0 auto; border:1px solid;text-align:center">
    <tr>
      <th>Valuta </th>
      <th>Iznos </th>
    </tr>
      {% for item in my_accounts %}
    <tr>
      <td>{{item.currency}}</td>
      <td>{{item.value}}</td>
    </tr>
    {% endfor %}
  </table>
  <br>
  <br>
  <br>
  <br>
  <br>


  <a href="{{url_for('auth.back')}}">Vrati se na prethodnu stranicu </a>
  </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Hello my firend</title>
    <meta name="viewport" content="width=device=width, initial-scale=1.0">
    <!--'Jinja syntax'  this is templates engine that flask uses-->
    {% block head %}{% endblock%}
</head>
<body>
 {% block body %}{% endblock%}
</body>
</html>

templates/convert.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Real Time Currency Converter</title>
	<style>
	    body, html {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;
        }
		.container {
		max-width: 500px;
		margin: auto;
		}

        a:link, a:visited {
        color: #221647;
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
        }
        p{
        font-family: serif;
        font-size:25px;
        color: #221647;
        }
        a:hover{
        border:1px solid black;
        }
        h1{
        text-align: center;
        font-size: 40px;
        color: #221647;
        font-family: serif;
        }
        .myDiv{
        height: 500px;
        width: 20%;
        border: 3px outset #221647 ;
        text-align: center;
        position: relative;
        top: 50px;
        left: 600px;
        }
        table, th, td {
        border:1px solid black;
        }
        .button {
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        }
	</style>
        <script>
        var inputKolicina = document.getElementById('inputKolicina');
        var inputValuta = document.getElementById('inputValuta');
        var outputVrednost = document.getElementById('outputVrednost');

        inputKolicina.onchange = function() {
        alert(inputValuta.value)
        outputVrednost.value = inputKolicina.value * inputValuta.value.value}
    </script>
</head>

<body>
  <div class="myDiv">

     <form class = "form-signin" action="/convert" method="post">
            <p for="inputKolicina" class = "sr-only"> Kolicina novca </p>
            <input type = "number" name="inputKolicina" id="inputKolicina" class="form-control" placeholder="Kolicina" required autofocus></br>

            <div class="form-group">
              <p>Valuta</p>
              <select name="inputValuta" id="sub_category_id" class="form-control">
                 <option value="" selected="selected"></option>
                  {% for currency in currencies %}
                  <option value="{{currency.currency}}">{{currency.currency}}</option>
                  {% endfor %}
              </select>
            </div>


            <p><input id="outputVrednost" name="value" readonly></p>
            <input type="submit" value="Konvertuj">
     </form>
        {% if error_message %}
        <p style="color:red">{{ error_message }}</p>
        {% endif %}
      <br>
      <br>
      <br>
        <a href="{{url_for('auth.back')}}">Vrati se na opcije</a>

  </div>
</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ulogovan</title>
    <style>
      body, html
      {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;

      }
      a:link, a:visited {
        color: #221647;
        background-color: rgb(194, 229, 235);
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
      }
      p{
        font-family: serif;
        font-size:28px;
        color: #221647;
        background-color: rgb(189, 238, 245);
        font-style: italic;
      }
      a:hover{
        border:1px solid black;
       }
       h1{
        text-align: center;   
        font-size: 40px;
        color: #221647;
        font-family: serif;
    }
    .myDiv{
      height: 400px;
      width: 20%;
      border: 3px outset #221647 ;
      text-align: center;
      position: relative;
      top: 50px;
      left: 600px;
      
  }
    </style>
</head>
<body>
  <h1>Zdravo, uspešno ste se prijavili!</h1>

  <div class="myDiv">
  <p>Opcije</p>
  <br>
  <a href="{{url_for('auth.status')}}">Pregled stanja</a><br/>
  <br>
  <a href="{{url_for('auth.update_profile')}}">Uredi profil</a>
  <br>
  <br>
  <a href="{{url_for('transactions.balance_check')}}"> Uplata sredstava na online račun</a>
  <br>
  <br>
  <a href="{{url_for('transactions.send_money')}}">Iniciranje nove transakcije drugom korisniku</a>
  <br>
  <br>
  <a href="{{url_for('transactions.history')}}">Istorija transakcija</a>
  <br>
  <br>
  <a href="{{url_for('auth.logout')}}">Logout</a>

  </div>
</body>
</html>

templates/editProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit profile</title>
    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
            background: center/cover  url("../static/bankingg.webp") fixed no-repeat;

        }
        
        .tabela{
            height: 500px;
            width: 45%;
            border: 3px outset beige ;
            text-align: center;
            position: relative;
            top: 50px;
            left: 100px;

        }
        table{
            width:45%;
            height: 450px;
            text-align:center;
            margin-left:auto;
            margin-right:auto;
        }

        label{
            color: azure;
        }

        a:link, a:visited {
            color: beige;
            text-decoration: underline;
            cursor: pointer;
          }
    </style>
</head>
<body>
    <a href="{{url_for('auth.back')}}">Vrati se na prethodnu stranicu <a/>

    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="tabela">
            <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="color: azure;">Podaci o nalogu</legend>

                <table>
                
                    <tr><td><label>Korisnicko ime</label></td><td> {{ form.username }}</td></tr>
                    <tr><td><label>Ime</label></td><td> {{ form.first_name}}</td></tr>
                    <tr><td><label>Prezime</label></td><td> {{ form.last_name}}</td></tr>
                    <tr><td><label>Adresa</label></td><td> {{ form.address}}</td></tr>
                    <tr><td><label>Grad</label></td><td> {{ form.town}}</td></tr>
                    <tr><td><label>Drzava</label></td><td> {{ form.country}}</td></tr>
                    <tr><td><label>Broj telefona</label></td><td> {{ form.phone_number}}</td></tr>
                    <tr><td><label>E-mail</label></td><td> {{ form.email}}</td></tr>
                    <tr><td><label>Lozinka</label></td><td> {{ form.password}}</td></tr>
                </table>
            
            </fieldset>
                <div class="form-group" >
                {{ form.submit }}
            </div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong style="color:red">{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong style="color:red">{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        </div>
                
    </form>
    
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device=width, initial-scale=1.0">
    <title>LOG IN</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
            background: center/cover url("../static/pozadina.jpg") fixed no-repeat;

        }

        h1{
            text-align: center;
            font-size: 36px;
            color: white;
            
        }
        .myDiv{
            height: 220px;
            width: 30%;
            border: 2px outset beige ;
            
            text-align: center;
            position: relative;
            left: 520px;

        }

        label{
            font-size: 25px;
            color: white;
        }

        a{
            text-align: center;
            font-size: 17px;
            position: relative;
            left: 590px;
            color: white;
        }
        
    </style>
    
</head>
<body>

    <h1>Prijava korisnika</h1>
    <div class="myDiv">
        <form method="POST" action="">
            {{ form.hidden_tag() }}<br>
            <label> E-mail </label><br>
            {{ form.email() }}<br><br>
            <label> Lozinka </label><br>
            {{ form.password() }}<br><br>
            {{ form.submit() }}
        </form>
        {% if error_message %}
        <p style="color:red">{{ error_message }}</p>
        {% endif %} 
    </div>

    
    <!--make this disappear when click start typing again-->
     {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert= {{ category}}} alert dismissible fade show" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
<br>
<br>
    <a>Niste registrovani? <a href="{{url_for('auth.register')}}">Registruj se sada</a></a>
</body>
</html>

templates/payIn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Provera statusa</title>
    <style>
      body, html
      {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;

      }
      a:link, a:visited {
        color: #221647;
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
      }
      p{
        font-family: serif;
        font-size:25px;
        color: #221647;
      }
      a:hover{
        border:1px solid black;  
       }
       h1{
        text-align: center;   
        font-size: 40px;
        color: #221647;
        font-family: serif;
    }
    .myDiv{
      height: 500px;
      width: 20%;
      border: 3px outset #221647 ;
      text-align: center;
      position: relative;
      top: 50px;
      left: 600px;
      
  }
  table, th, td {
    border:1px solid black;
    

  }
  .button {
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
  
  .button1 {background-color: #008CBA;} /* Blue */
    </style>
</head>
<body>
  <h1>Uplata sredstava putem platne kartice na online račun</h1>
  <div class="myDiv">
    <br>
  <table width="90%" style="margin: 0 auto; border:1px solid;text-align:center">
    <tr>
      <th>Trenutni iznos na Vašoj platnoj kartici: </th>
    </tr>
    <tr>
      <td>{{payment_card_balance}}</td>
    </tr>
    <tr>
        <th>Trenutni iznos na Vašem online racunu: </th>
      </tr>
      <tr>
        <td>{{acc_balance}}</td>
      </tr>
  </table>
  <br>
  <p>Koliko para želite da prebacite na online karticu?</p>
    <form method="POST">
      {{form.amount}}
      {{form.submit}}
    </form>
  <br>
<!--  <button class="button button1">Prihvati</button>-->
  <br>
  <br>
  <br>
  <br>
     {% for mesg in get_flashed_messages() %}
      <h1>{{ mesg }}</h1>
      {% endfor %}
  
  
  <a href="{{url_for('transactions.back')}}">Vrati se na prethodnu stranicu </a>
  </div>
</body>
</html>

templates/statusCheck.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Provera statusa</title>
    <style>
      body, html
      {
        height: 100%;
        margin: 0;
        background: center/cover url("../static/bank.jpg") fixed no-repeat;

      }
      a:link, a:visited {
        color: #221647;
        text-decoration: underline;
        cursor: pointer;
        font-size:20px;
        font-family: serif;
      }
      p{
        font-family: serif;
        font-size:25px;
        color: #221647;
      }
      a:hover{
        border:1px solid black;  
       }
       h1{
        text-align: center;   
        font-size: 40px;
        color: #221647;
        font-family: serif;
    }
    .myDiv{
      height: 300px;
      width: 20%;
      border: 3px outset #221647 ;
      text-align: center;
      position: relative;
      top: 50px;
      left: 600px;
      
  }
  table, th, td {
    border:1px solid black;
  }
  
  .button {
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
  
  .button1 {background-color: #008CBA;} /* Blue */
  .button2 {background-color: #5c0000;}
    </style>
</head>
<body>
  <h1>Pregled stanja računa</h1>
<!--treba dodati logiku da li je novi korisnik ili stari, trenutno se podrazumijeva da je novi-->
  <div class="myDiv">
    <br>
  <table width="90%" style="margin: 0 auto; border:1px solid;text-align:center">
    <tr>
      <th>Trenutni iznos na vasem racunu je: </th>
    </tr>
    <tr>
      <td>{{balance}}</td>
    </tr>
  </table>
  <br>
      <a href="{{url_for('auth.account_verification')}}" style="visibility:{{visibility}}">
        <button type="submit" class="button button1">Verifikuj nalog</button>
      </a>

	  <a href="{{url_for('auth.convert')}}">
        <button type="submit" class="button button2">Konvertuj</button>
  <br>

      </a>
      <a href="{{url_for('auth.balances')}}">
        <button type="submit" class="button button2">Pregled ostalih racuna</button>
      </a>
      <br>
      <br>



  <a href="{{url_for('auth.back')}}">Vrati se na prethodnu stranicu </a>
  </div>
</body>
</html>